### PR TITLE
Dimmable Backlight for RT3 / MD380

### PR DESCRIPTION
**Pull request by Wolf-DL4YHF**
ten backlight intensities selectable in menu,
realized via UART6_TXD on PC6,
abused to generate PWM with 5 .. 100 % duty cycle.
'evolution' : see google group

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
Howdy @Wolf-DL4YHF!  We should get this running on S13.020 before merging.  Do you have hardware for that, or should I take a stab at making it compatible?

73 from New York,
KK4VCZ

**Comment by Wolf-DL4YHF** [comment]
Hello Travis,

Nice to hear from you for the first time. Unfortunately I only have an 
RT3, and none of the fellows around has a GPS unit.
I noticed a small bug in the implementation ("zero" in the config 
structure, leaving the operator with an all-black screen that makes it 
difficult to enter the MD380Tools menu at all).
Does it cause a much of work for you and the core devs if I "request a 
pull" again with a slighly modified version ?

I considered this: If we had a of "sizeof( addl_config )" stored in the 
first byte of struct addl_config itself,
any new application would have the chance to find a parameter was 
already set the previously installed firmware
(because "global_addl_config.my_size >= sizeof( addl_config )"),
and if not (size stored in the SPI flash smaller than the size in the 
new firmware),
populate its own, new member (e.g. backlight_intensities) with a 
meaningful default.

In this case, the set idle backlight to '1', and the active backlight to 
'5', or similar.

Unfortunately this is incompatible as you noted to newbies (because the 
byte at offset zero is already used for 'crc').
Or am I missing a point, and 'crc' in the first byte would automagically 
detect a size mismatch, and fill the entire struct with zeroes ?

Greetings from Germany,
   Wolf DL4YHF .

Am 10.01.2017 um 17:38 schrieb Travis Goodspeed:

**Comment by travisgoodspeed** [comment]
Howdy Wolfgang,

Please take a few days to merge any last changes into Wolf-DL4YHF:DL4YHF-Backlight, then make a comment here telling me to begin porting it to S13.020 and merging.

Cheers,
--Travis

**Comment by Wolf-DL4YHF** [comment]
RRR Travis,
ok. Someone asked me if the lowest intensity can be reduced even more, 
and a few changes in SysTick_Handler() may do the trick.
The changes won't be "dramatic", I only expect to modify irq_handlers.c .
So all the rest (finding the patch addresses for SysTick_Handler in 
S13.020) should not be affected by this.

Thanks for the amazing work & see you later,
   Wolfgang "Wolf" DL4YHF .

Am 10.01.2017 um 18:13 schrieb Travis Goodspeed:

**Comment by dl2new** [comment]
Hi Wolf, I compiled your "Backlight-branch" for my md380. I see menu entries "Backlt low/gigh/tmr" but without without function. Only display on or off (dark). Any ideas? 73 de Sven, DL2NEW

**Comment by Wolf-DL4YHF** [comment]
Hi Sven,

Can you try the compiled binary on my website ? The firmware needs a 
patched interrupt vector table, which is achieved by a modified Python 
script. I had included that script in my branch at Github, but didn't 
check if the script is really invoked from the makefile.
The file 'experiment.bin' from
http://www.qsl.net/dl4yhf/RT3/dl4yhf_weak_backlight_experiment.zip
definitely contains all necessary patches (make sure you get a fresh 
one; in this archive the timestamps are real).
Anyway, my temporary branch at github will be updated in a few days 
after adding another, even darker backlight (a 'night owl mode'). In the 
meantime I had modified so many things back and forth that the sources 
need to be cleaned up before committing / pushing them again, to become 
merged with Travis' "official branch" again (there's no need for a 
permanent fork).

All the best,
   Wold DL4YHF .

Am 12.01.2017 um 17:57 schrieb Sven:

**Comment by dl2new** [comment]
Hi Wolf, thanks for the link. I uploaded the experimental.bin from the zip-file with "md380-dfu upgrade experiment.bin". But same behavior: no dimmed sreen - only off or on. Add ideas/hints? 73 de Sven, DL2NEW

**Comment by Wolf-DL4YHF** [comment]
Hi Sven and all,
I temporarily switched back to the earlier "GPIO bitbanging PWM". By the 
time you read this it should be on the 'Wolf-DL4YHF' repo, and (compiled 
into dl4yhf_weak_backlight_experiment.zip/experiment_PWM_via_GPIO.bin) 
on my page at qsl.net .
The 'GPIO-variant' produces a PWM with only 74 Hz. The UART-variant uses 
220 Hz (approximately).

I noticed that both variants suffer from the same problem in the menu 
("Backlt low" + "Backlt high") :

The 'blue disc' that marks the currently selected item doesn't properly 
follow the vertical scrolling position.
Only the blue marker bar marks the current setting (before navigating 
with the cursor keys).
The same effect could sometimes be seen in other menus (iirc the date 
format selection). Didn't look it up yet, maybe there's a topic already 
existing for this in the google group.

Guess we should postpone any attempt to merge my temporary branch; I 
need a better understand how the menu functions are supposed to work.

73,  Wolf .

Am 12.01.2017 um 20:17 schrieb Sven:

**Comment by Wolf-DL4YHF** [comment]
Hi Sven and all 'dimmed backlight testers',

I have reduced the UART baudrate so the PWM frequency is 104 Hz now.
It's in my temporary branch on Github, but also (for convenience) in the 
zip file at
   http://www.qsl.net/dl4yhf/RT3/dl4yhf_weak_backlight_experiment.zip

There are two variants of the backlight at the momemt, one producing the 
PWM "via GPIO" and one "via UART".
The PWM frequency of the UART-variant is 104 Hz now, the GPIO variant 
produces 74 Hz ( SysTick frequency, 666.6 Hz / 9 ).

If the UART variant still doesn't work on your radio please try the GPIO 
variant, from the zip archive:
     experiment_PWM_via_GPIO.bin .

As before, both are ONLY for RT3 / MD380 (non-GPS). I added support for 
the GPS devices, based on the S13.020 firmware, including the necessary 
patches in the 'merge' scripts, but I cannot test them.

All these are contained in the Github repo now. In the repo, a switch is 
already set to compile the interrupt handler (SysTick_Handler) for the 
UART variant because (unlike the GPIO variant) it doesn't flicker at all.

Besides these pending tests, the temporary 'backlight' branch is ready 
for being merged into the master.
I would prefer to have it merged back before beginning to play with the 
microphone gain and audio signal paths.

Greetings from snow-covered Germany,
   Wolf .



Am 12.01.2017 um 20:17 schrieb Sven:

**Comment by dl2new** [comment]
Hi Wolf. Thanks for your work. The GPIO version runs fine but the UART version not. I use a md380. 73 de Sven, DL2NEW

**Comment by Wolf-DL4YHF** [comment]
Hi Sven,

Thanks, that's interesting. Something I would not have expected. So 
maybe Tytera's part of the firmware reprograms the UART registers in 
certain situations (here, it does not, which I checked by reading back 
all USART6 registers via USB).

73,
   Wolf DL4YHF .

Am 15.01.2017 um 22:13 schrieb Sven:

**Comment by Wolf-DL4YHF** [comment]
Can one of the core devs make sense out of this:
The dimmed backlight only works if
 "Utilities".."Radio Settings".."Intro Screen" is set to "Char String".
When set to "Picture", it does not. I guess that's because splash_hook_handler() isn't called then.
Is there another hooked function already called *once*, shortly after booting, but *after* Tytera's own SystemInit() has reset most on-chip peripherals in the STM32F4 ?

Cheers,
  Wolf .

**Comment by travisgoodspeed** [comment]
Howdy @Wolf-DL4YHF,

We are almost certainly hooking the wrong init routine, as the character strings were the first to be identified when first reverse engineering the firmware.  We can fix this by moving the splash hook to the parent function.

I can find that function when I find some time without distraction.  Maybe tomorrow?

How is the rest of the patch looking?

--Travis

**Comment by Wolf-DL4YHF** [comment]
Hi Travis,

Yes I also think the existing hook (which btw was the only one i saw, 
already existing) is possibly the wrong one.

Besides that, the rest of the patch for the dimmed backlight works 
nicely, on two different radios (I tried it on one which never had a 
patched firmware loaded before, and the default settings work properly now).

In the past days I dug deeply into the original firmware to find the 
right hook (my bet is in the 'Start' - task) but there is one remaining 
concern:
We possibly need to initialize "our" interrupt handlers twice (which is 
ugly but seems unavoidable):

- first *before* Tytera's SystemInit() & Co, to have the backlight (and 
other interrupt services) enabled during "our" early display .. 
scrolling bitmap on the welcome screen, etc

- a second time *after* Tytera's ResetHandler(), SystemInit(), etc, 
because those functions and anything called from there will possibly 
'undo' any on-chip peripheral initialisation, via the RCC's "peripheral 
reset register". Many Cortex startup functions I've seen over the years 
leave "nothing to fate", and reset almost everything (via the RCC, which 
is simply done by writing a couple of ONEs into those registers).

We will sooner or later experience similar when integrating Morse code 
output in our own interrupt handlers.. it's of my next projects 
(providing the morse output; retrieving the text of the currently 
selected channel is another story - too difficult for me at the moment).

So here's my suggestion: Find out where to call our init function 
(applet/src/irq_handlers.c : IRQ_Init), and merge any 'future' 
interrupt-handler-initialisation into that module.

Cheers,
   Wolf .

Am 31.01.2017 um 14:32 schrieb Travis Goodspeed:

**Comment by Wolf-DL4YHF** [comment]
What can I do to resolve the above conflicts ?
My dimmed-backlight branch is quite old now .. would it be easier for those with write-access to the main branch to delete this PR completely, make a new clone from the recent master, and apply my modifications again (to have less differences) ?
I'm not keen on diverging further away from the master before starting the next 'creative work', which I want to be based on the master branch, instead of being a fork from a fork ... 

Cheers,
  Wolf, DL4YHF .

**Comment by travisgoodspeed** [comment]
@Wolf-DL4YHF Apologies for taking so long with this patch.  Things have been pretty hectic lately.

I've pushed a patch that hopefully fixes with the merge conflicts without breaking anything.  If there are conflicts left, I'll fix those up and then we can mere to master.

**Comment by travisgoodspeed** [comment]
My patch broke `merge_s13.020.py` and `merge_d02.032.py`.  Probably unmatched paren or mixed indentation.

**Pull request merged**
