### PR TITLE
New small latin font; md380-gfx bug fix for small font 

### PR DESCRIPTION
**Pull request by maushammer**
md380-gfx bug fix - height stored in table was 2x what it should have been for small fonts (12 instead of 6). I apparently missed this in my binary testing, but the software in the unit seemed to work.

Small latin characters - performed _serifectomy_ on letters, using the Apple ][ font as a general reference. I am unable to test with an actual unit; feedback on how the letters look is requested!

### CODE REVIEW

**Comment by aeickho** [comment]
MD380 font
f2
@maushammer font
f2

**Comment by aeickho** [comment]
in a few minutes there is a new software

**Comment by aeickho** [comment]
Hi John,
an test branch... that's used your new font 
https://github.com/aeickho/md380tools/tree/usersdb_in_spi_flash

With no users.csv in spiflash test chars will be displayed instead of the transmitter status info.

To Import the users data:
`wc -c < db/users.csv > data ; cat db/users.csv >> data  # generate data file`

and flash the data file to the spiflash with:
` ./md380-tool spiflashwrite data.txt 0x100000 `

**Comment by maushammer** [comment]
Whoa, that's awesome Alex - thank you!!

Give me a few days & I'll fix up the font & resubmit!

**Comment by aeickho** [comment]
One problem the handling of Unicode character in the users.CSV  also the handling  of character there  are not in the font

**Comment by aeickho** [comment]
this version is merged with f991d9b21a06ffd897402b3691302acfc102acba

**Comment by travisgoodspeed** [comment]
Closing this pull request, as @aeickho already merged it in f991d9b21a06ffd897402b3691302acfc102acba.  (Is Github's merge detection confused?)

**Comment by dysinger** [comment]
You'll notice that the font does not render upper case J properly (screenshots above).  This confused me for a little while until I noticed what was going on. Should we reopen this ticket or create a new one?

**Comment by dysinger** [comment]
Actually it's both fonts in both screenshots

**Comment by dysinger** [comment]
lower case j is also chopped off

**Comment by dysinger** [comment]
looks like g, q and p too. I'll open a new ticket.

**Comment by maushammer** [comment]
Sorry I've been slow on this. It looks like the uppercase J was defective from the factory - I've been meaning to fix this. I think the other lower case characters will render correctly with another change (yesterday?, sorry on mobile) that drew the extra rows.

**Pull request closed without merging**
