### PR TITLE
Netmon timestamp fix, MD-446 keyb support, mic gain feature and minor bugfixes

### PR DESCRIPTION
**Pull request by DL2MF**
- Netmon 4/5 timestamp fix, time was missing during QSO when netmon mode was activate screen
- Support for Tytera MD-446, the version of MD380 with a reduced keyboard (no numeric keypad)
- Frequently used new features (backlight, mic gain, talkgroup) put to the end of tools menu (to be accessed by a single arrow up keypress, no need to scroll the full menu)
- New Mic Gain feature (off, 3dB, 6dB) from KG5RKI fork implemented

### CODE REVIEW

**Comment by DL2MF** [comment]
@travisgoodspeed looks like something in Travis CI failed due to a missing compiler package ...

**Comment by KG5IEN** [comment]
@DL2MF : I got that same error while working on #745 ; the whole toolchain directory was missing from http://px4-travis.s3.amazonaws.com/ for somewhere between a few hours and a day before they showed back up again.  It might be worth filing an issue about if we control where we pull that package from...

**Comment by DL2MF** [comment]
@travisgoodspeed Howdy Travis, any idea what might have failed? Like KG5IEN noticed us, he ran into the same issue a few PR's ago. I don't see how this could be affected by my code changes, that was made from a fresh clone of @Wolf-DL4YHF latest commit from last weekend.

**Comment by travisgoodspeed** [comment]
Looks like it's failing to compile against 2.032 firmware, probably because of a symbol that is only defined on more modern targets.

You can fix this by judicious use of #ifdef, or maybe it's time to finally say goodbye to 2.032.  (We've kept it around only because it's easy to get running on new hardware.)

**Comment by DL2MF** [comment]
@travisgoodspeed Has been fixed, I first had no closer look on it due to the Mac OS X Travis CI issue I got starting the pr 4 days ago, that was the same issue KG5IEN reported.

**Comment by Wolf-DL4YHF** [comment]
Beware, your addition in SysTick_Handler may be unsafe.
You added a new keyboard-calling function called from SysTick_Handler, which calls ...

PollKeysForScroll -> ..... -> handle_hotkey().

handle_hotkey() seems to draw something on the screen (clog_redraw), changes gui_opmode1 + 2, etc.

Since SysTick_Handler() is called 666 times per seconds, and we can expect that it may be called "anywhere". It also interrupts the currently running task.
Setting a flag in SysTick_Handler is ok, but anything that possibly takes several milliseconds must not be done there.

Such problems won't happen immediately. But sooner or later a SysTick (interrupt) will fire when you don't expect it, and .... "bang". That why anything else in irq_handlers.c pedantically avoids calling anything that may call something in the original firmware, of course except the original SysTick_Handler.

**Comment by DL2MF** [comment]
Thanks for your advice, did you experience any issues or notice any unreasonable inconsistency? 

This build has been tested very in-depth and you might have noticed, that PollKeysForScroll() is being called every 111th SysTick, what is far enough for cursor scrolling. Due to my awareness I already made a very huge scrolling test to check for timing issues, continuously scrolling within menus (not only MD380tools menu), contacts, zones several hundred times, with stucked keys, without and for several minutes, as long as my finger could press the keys.

This firmware is running since a week on my two MD-390/G and a MD-446, both types very extensively in use and currently all radios work fine.

My latest pull request now also includes the user-selectable keyb layout for MD-3x0/MD-446 inside the option menu, no need any more to compile separately firmware for the MD-446. This might also be a lookahead for upcoming new models supported by MD380tools.

**Comment by Wolf-DL4YHF** [comment]
Hi Mike,

>> you might have noticed, that PollKeysForScroll() is being called every 111th SysTick

Of course, but it doesn't matter. Even if only every 111 th SysTick calls a function in the original firmware that isn't re-entrant, or runs in a task that isn't designed to be called from anywhere else, your're asking for trouble.

**Comment by DL9SK** [comment]
Is there a problem why DL2MF changes because it takes so long time for merging. It would be greatfull that we can use the new menu and microphone loudness enhancement. 73 Ralf DL9SK

**Comment by sijskes** [comment]
@DL9SK it could be because this pull request contains a lot of commits for different issues. i you want quick commits, that are easy to commit for a reviewer, you should pull request 1 issue at a time.

**Comment by roelandjansen** [comment]
wta @sijskes says. It's hard to review -- PR per issue would be OK.

**Comment by DL9SK** [comment]
Thank you very much for your quick answers. Now I understand it.

73, Ralf DL9SK

**Comment by DL2MF** [comment]
@travisgoodspeed Hi, any progress concerning the reviewof my PR's? I did put my further activitities for MD-2017 support on hold due to the massive changes in my pending PR's. Waiting for the flexible keyboard system (with MD3x0 and MD446 but included as a prerequisite feature for further radios), new menu and HRC5000 support of advanced FM features in the official builds before continue working on other options.

**Comment by DL2MF** [comment]
This is a summary of my PR #762 #781 #782 #783 #784 and minor cleanup of some development comments. This build has been tested and requested by many users, how did download this during the last 2 1/2 months already from my site and asking for official builds.

Extended FM features, new menu and all other funtions are documented here:
[http://dl2mf.de/md380tools/](url)

This branch is also a prerequisite for my latest additions with SMS feature support for BrandMeister messaging gateway 262993/262994 providing TG, WX and GPS report SMS. The feature is also ready for a PR but needs to finish this before.

**Comment by travisgoodspeed** [comment]
If anyone has objections to merging this PR, speak now or forever hold your peace.  I'll be clicking the merge button in twelve hours.

**Pull request merged**
