### PR TITLE
Added functions to side programmable buttons. Also broke out unused TIM12 interrupt.

### PR DESCRIPTION
**Pull request by claywalker0929**
Added ability to set side buttons to our own functions
Added first new side button function: enable/disable backlight
Broke out TIM12 interrupt to be used for our own functions, however it is unused as of now.

To change sidebutton function:
./md380-dfu read codeplug.bin
./md380-codeplug sidebutton ? (for usage)
./md380-dfu write codeplug.bin

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
I like it, but this patch looks like it will only be functional on D13.020 and we ought to also have it working on S13.020.  Do you have hardware with GPS available, or should I take care of digging up the missing symbols?

Menu integration for the new button feature would also be nice, but that can wait until after the merge.

**Comment by claywalker0929** [comment]
Hey Travis. Unfortunately I don't have the hardware for it. If someone could create a few different codeplugs and give me their corresponding RAM dump, I'd be more than happy to do the leg work. Or else you can, no worries. Thanks!

**Comment by travisgoodspeed** [comment]
I'll push a core dump from an S13 radio this evening.

**Comment by claywalker0929** [comment]
Hey Travis, when you get a chance can you check this out? S13 support should be done thanks to a friendly gentleman on the google group. Thanks.

**Comment by travisgoodspeed** [comment]
Excellent!  The code looks nice and clean, and I expect to merge it after verifying the behavior on real hardware.

(I'd very much like to have the side button controlled by MD380 menus, rather than just the new `md380-codeplug` script, but I won't hold the merge back for it.)

**Comment by DL2MF** [comment]
I can check this on my MD390/G, is the repo in your fork up to date Clay?

**Comment by claywalker0929** [comment]
Yes. My master branch is up to date. If you can change the button
functions, that means it is working. If not, let me know. Thanks!

On Tue, Jan 17, 2017, 5:03 AM Mike <notifications@github.com> wrote:

I can check this on my MD390/G, is the repo in your fork up to date Clay?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/travisgoodspeed/md380tools/pull/652#issuecomment-273146694>,
or mute the thread

**Comment by DL2MF** [comment]
@travisgoodspeed @claywalker0929 just flashed my MD390 with the master-branch and it works from scratch with flash_S13. Menu entry used to set side button "Top pressed" to "toggle backlight" and "manual dial", works like a charm.
Only settings of "Top held" seems to hazzle with "Top pressed", a long(er) press on the key calls the short press function, but this is not a showstopper for now I think.

**Comment by DL2MF** [comment]
Cross check with the Tyt CPS show, all assignments are fine. I have learned, you are using "unassigned" for backlight toggle and "vox" for the Zone increment.

The long press on "Bottom Held" is working fine, only the "Top Held" seems to need another key assignment, will look for it when finished my latest own changes.

**Comment by DL2MF** [comment]
... curious, just assigning again  "Manual Dial" and "Power Low/High" to Top press/hold, now everything works fine assigned to both buttons.

**Comment by claywalker0929** [comment]
Regarding the held function muddling with the short press, I was noticing that last night too. That will take a little more investigation. I don't believe my code would interfere with the factory functions like that. I will test on original firmware.

As for the CPS software, I (ab)use the factory firmware codeplug locatio, so CPS will probably report the button as unassigned when in reality it is one of our custom functions. However, the vox vs zone increment I will look in to. That must be a bug on my part.

**Comment by DL2MF** [comment]
In the meantime I made some extended tests with 3 MD390/G available here. The only conflict seems to affect scanmode. When scanmode enabled, the long keypress doesn't work, but this seems to be caused by the original firmware.

I did implement your side-buttons fork and my last netmon changes from my latest PR all into a single fork and were using both on the 3 testradios without problems for the last 2 days. I really like your feature, this gives another benefit to this nice radio.

Together with Wolf's modification of backlight dim, it would be nice, to use one of the sidebuttons to toggle the backlight by short press from a maximum value stored in setup within 2-3 few steps to off by repetitive button pushes.

**Comment by claywalker0929** [comment]
Thanks, I appreciate your help. I did some testing also, some button
combinations work just fine and some require a longer press. I think I'm
going to keep looking, I have a question though, what version of CPS
software do you have? I could not replicate the vox vs zone increment
button reporting that you saw in the CPS software. I grabbed all my values
straight from codeplugs written with version 1.32.

That's fine about the fork. We can make one large merge.

But that's a great idea with Wolf. I'll work with him and we can get a new
function added. Probably after both of these PRs go through.

**Comment by DL2MF** [comment]
Yes, that was what I wanted to notice you about, I'm already on CPS 1.36, have noticed somewhere reports about differences between 1.3x <> 1.36 and minor issues with some functions.

I'm using this CPS version for more then 3 months without any other trouble. My codeplug edited by this version is also in use by several friends with MD380's. I have programmed about 10 different radios with that version, the latest was the 3rd MD390/G I just have for testing available from a friend. This is a radio from the new batch which had S013.032 stock firmware.

**Comment by claywalker0929** [comment]
Hey Mike, I still haven't seen the issue with the CPS software. Can you verify it is still a bug and maybe attach some screen shots or something. I might be misunderstanding it. 

However, I did just push an update that fixes the muddling between short and long presses. If someone could verify it works on S13 hardware I would really appreciate it. After it's verified, I believe this functionality is done for the time being.

**Comment by DL2MF** [comment]
Good morning, I just did check it again on my business laptop with CPS 1.36 and the same result.

1. assigning side buttons in md380tools menu
2. readings codeplug with CPS 1.36
3. checking button assingment

grafik

If it's helpful for you I can send the .rdt file to you, please mail me at dl2mf@darc.de

I will test your latest fixes tonight when I returned home from work, cause I don't have md380tools development environment available at work.

**Comment by claywalker0929** [comment]
Found it thanks. I thought I had the most recent software, but I found CPS 1.36 on a different site than the tyterra site. Oh well. There are two different functions that change the zone. CPS 1.32 had zone increment, which just incremented the zone, Zone toggle toggles between the first 4 zones with beeps indicating what zone is selected. The part that gets screwy is zone toggle replaced zone increment in CPS. I have included both functions in the menu because one might work better for someones situation and for backwards compatibility reasons. Also added the battery indicator function available from CPS 1.36. I guess that beeps up to 3 times indicating the current battery level. Thanks Mike. That should be about it for this assuming S13 functionality works as expected.

**Comment by claywalker0929** [comment]
What's the status on this? Has anyone else tested this and come up with any bugs? Otherwise I feel this patch is ready for primetime. I'm hoping to get another unrelated small patch in after this, but it would be nice if this were merged first.

**Comment by travisgoodspeed** [comment]
I'll merge this tomorrow after checking it on hardware.  If anyone else could look for a merge conflict as well, I'd appreciate that.

**Comment by DL2MF** [comment]
I've been using my build from the latest PR's of Clay, stargo and myself (#652, #663, #674) now for more than 2 weeks (1 week for #674) without any trouble on 3 different MD390G. One radio was in daily usage, another has been tested by another friend, all radios are running fine with all mods.

**Pull request merged**
