### PR TITLE
Change "original" date sep char for ISO 8601

### PR DESCRIPTION
**Pull request by nivex**
https://en.wikipedia.org/wiki/ISO_8601
https://xkcd.com/1179/

### CODE REVIEW

**Comment by sijskes** [comment]
@nivex  can you also fix the actual date presentation in gfx.c

**Comment by sijskes** [comment]
@nivex better yet, create extra menu entry for: global_addl_config.datef == 4

**Comment by NicoVarg99** [comment]
I tried. If you add more than 4 entries in the menu it doesn't scroll down to let you see the others.
Maybe I'm doing something wrong?
I'd like if the YYYY/MM/DD wasn't replaced with YYYY-MM-DD. I'd rather suggest to keep both of them.

In the photo you can see that it shows only 4 options (but the code tells to show 5!) and you can't scroll.
photo275275153220415201

**Comment by sijskes** [comment]
@NicoVarg99 do you have branch with code somewhere?

**Comment by NicoVarg99** [comment]
https://github.com/NicoVarg99/md380tools

**Comment by NicoVarg99** [comment]
Updated.
There is still a bug (when moving through entries the wrong one gets selected as you scroll down).
@sijskes please check.

**Comment by aeickho** [comment]
@all ... 
there is a dialog menu with more than 4 radio boxes? on original fw? 
then we could see how they do it....

**Comment by NicoVarg99** [comment]
The "Zone" selector's got a lot of entries.
btw I have no idea at all how to see how they do..

**Comment by aeickho** [comment]
Update:  .. yep Programm-Radio - Time Out Timer ----> more the 4 radio buttons

**Comment by aeickho** [comment]
zone is complicate ....   this is an dynamic generated list ...

**Comment by aeickho** [comment]
to look@ the Create Programm-Radio - Time Out Timer Menu Entry ...: 

this is a way to look at what we / I go wrong do:)

**Comment by aeickho** [comment]
btw... I spent my free time temporary to add the  S13.020 fw...  so my help is limited

**Comment by aeickho** [comment]
some additional note: 
the variable name  ... maybe md380_menu_0x200011e4 based on the memory address of fw: d02.032

symbols_d02.032
md380_menu_0x200011e4                  = 0x200011e4; /* from D002.032 @ 0x80127f4 func 0x80127d0 */

src/symbols_d13.020
md380_menu_0x200011e4                  = 0x20004acc; /* */

this is a little confuse... but this was my way to learn more about die menu structure

**Comment by aeickho** [comment]
see 0x08016320 @ d13.020  Create Time Out Menu ... it is also dynamic and not with x * F_249_Create_MenuEntry()

**Comment by aeickho** [comment]
question ... what is on ram adreess 0x2001e0d0  ... md380-tool hexdump 0x2001e0d0

**Comment by sijskes** [comment]
Functionality is included in https://github.com/travisgoodspeed/md380tools/pull/249

**Pull request closed without merging**
