### PR TITLE
changed permissions of the device udev rules permissions from 0666 to…

### PR DESCRIPTION
**Pull request by roelandjansen**
changed permissions of the device udev rules permissions from 0666 to…… 0660. More secure

### CODE REVIEW

**Comment by sijskes** [comment]
Can you do, with the patch applied and the md380 pluged in and turned on:

find /dev -ls | grep usb

id

and report this back?

also do

sudo getfacl /dev/bus/usb/xxx/yyy

replacing the xxx and yyy with the relevant paths.

and report this back?

**Comment by sijskes** [comment]
that is on suse, i mean.

**Comment by roelandjansen** [comment]
with a slightly modified line to prevent diversity in distributions.

ACTION=="add", SUBSYSTEM=="usb_device", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", GROUP="dialout", MODE="0660"
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", GROUP="dialout", MODE="0660"

and the flashing user in the dialout group:

both on debian and suse (fedora is in the wait but expect the same results)

debian:                                                                                                                                                                                                                                                           
                                                        

getfacl: Removing leading '/' from absolute path names
# file: dev/bus/usb/002/007
# owner: root
# group: dialout
user::rw-
group::rw-
other::---

suse

getfacl: Removing leading '/' from absolute path names
# file: dev/bus/usb/001/010                                                                                                                                                                                                                                                 
# owner: root                                                                                                                                                                                                                                                               
# group: dialout                                                                                                                                                                                                                                                            
user::rw-                                                                                                                                                                                                                                                                   
group::rw-                                                                                                                                                                                                                                                                  
other::---

**Comment by roelandjansen** [comment]
security seems not to be interesting. closing as #WONTFIX.

**Comment by travisgoodspeed** [comment]
Howdy y'all,

It's not so much a matter of security as that we are only supporting hobbyists on mostly single user systems. Ham radio largely functions because folks agree not to be jerks to one another, and even though our repeaters could easily be jammed we rarely suffer more than the occasional troll. 

If we ever support the radio on multi-user systems, such as a club server, then we'll include a section in the configuration guide for it.  For now, I'd rather not complicate the installation at the cost of more support requests.  666 permissions work well for software defined radios, and they should remain the default here.  The permissions can be reduced as needed on multi user machines.

Closing this issue.

73 from Buda,
-Travis HA/KK4VCZ

**Pull request closed without merging**
