### PR TITLE
Morse output for visually impaired hams

### PR DESCRIPTION
**Pull request by Wolf-DL4YHF**
.. plus an 'alternative' menu supposed to be easier to use, less deeply nested, and the most important item-VALUES are immediately visible ( / readable in Morse code) without the need to enter a submenu or extra dialog / "confirm" screen.

May become the framework to open Netmon screens. Already allows entering an 'ad-hoc' talkgroup number on the fly (also via programmable sidekey, based on PR #708), without entering Tytera's menu. Similar planned (with a whitesticker-friendly user interface) also to enter an ad-hoc *reflector* number. 

Unresolved issue with interference from channel scanning: During a message in Morse code, the audio PA must be enabled. If, during that time, channels are scanned, there's a hell of a noise originating from the demodulator (or DMR chip). Still looking for a way to *temporarily* disable channel scanning without turning it off in the config.

Take your time with merging - this branch isn't fully finished and will possibly take a few weeks until other plans (by DL4YHF) have been put into the code.

### CODE REVIEW

**Comment by Wolf-DL4YHF** [comment]
The alternative ("Morse-output-friendly") menu is making good progress.
Turns out a nice way to edit the talkgroup ad-hoc, and can be flawlessly invoked from any programmable sidebutton. All credits to Brad for PR #708; I have 'assimilated' his pending PR in mine. 
The in-place editor (which allows editing any numeric value in the menu) needs some polishing, but will be finished / published soon.
If anyone else is also working on the 'Set Talkgroup via sidebutton' feature : Let's coordinate this here, don't  re-invent the wheel. Ok ? 
73, Wolf .

**Comment by Wolf-DL4YHF** [comment]
Github is driving me crazy. It shows sooo many merge conflicts where just trivial modifications (which I am cannot fix or resolve myself because I don't have write-permission to the original master, even for those modules I wrote myself (like irq_handlers.c). I give up. This automatic 'merge conflict detection' is just TOO PEDANTIC. Please delete this PR, I will try to create a new branch from the current master (travisgoodspeed), and try to merge everything. Or will maintain my own fork from now on, which may be easier (for everyone involved !) than merging a branch based on a two-month old repository.

**Comment by travisgoodspeed** [comment]
Sorry for Github's complications, neighbor.  I'll give you commit rights tonight in the hope that will make things smoother.

(Aboard a flight now, so it might take a few hours.)

**Comment by Wolf-DL4YHF** [comment]
Ok, then I can focus on more creative work than this...
  Cheers, 
    Wolf .

**Comment by docprofsky** [comment]
The way GitHub resolves merge conflicts on the website is by merging the target branch into the submitted branch and having you resolve those conflicts. So, if you want to merge the branch `feature` into `master` and there are conflicts, it will have you merge `master` into `feature` then merge the result of that into `master`.

I would recommend merging from git directly. To do this you need to have `travisgoodepeed/md380tools` cloned and add your fork as another remote (`git remote add https://github.com/Wolf-DL4YHF/md380tools.git`). To get the latest updates from your fork, run `git fetch Wolf-DL4UFH`.

To merge:
- Ensure you have the latest changes for the branch that you want to merge into (travisgoodepeed/md380tools@master)
  `git checkout master`
  `git pull`
- Get the latest changes from your branch
  `git fetch Wolf-DL4YHF'
- Do the merging
  `git merge --no-ff Wolf-DL4YHF/master`
  This should list files where it had conflicts.
- Fix the conflicts
  Use `git status` to see what files have conflicts; these will be listed under `Unmerged paths:`.
  Once you have fixed the conflicts in a file, mark it as resolved by running `git add <path to file>`.
  If you want to restore the state of a file to when you started the merge (a mistake was made when resolving the conflicts), run `git checkout -m <path to file>`.
- Finish merging
  Run `git commit` to finish the merge.
  To push the results to `travisgoodepeed/md380tools` run `git push`.

**Comment by Wolf-DL4YHF** [comment]
Hi Travis,
Thanks, and I promise to be careful. I have forked the main repository 
to remove some of my own (internal) commits and their descriptions, 
which nobody will read anyway. In the meantime there's not only the 
Morse output, but also an alternative menu (with its own, independent 
LCD driver) which makes adding new features and easier. But more on that 
later.

Cheers,
   Wolf .



Am 07.05.2017 um 23:20 schrieb Travis Goodspeed:

**Comment by Wolf-DL4YHF** [comment]
Hi there,
Thanks for the info. Basically this is what I had been using in earlier 
development steps, but this time, I got flooded with merge conflicts 
which (to me) didn't make sense at all. Well, most of them have been 
fixed in the meantime.

Looks there were just too many subsequent changes, all of them 
documented very frequently by myself (for each and every module written 
in the meantime, related with the Morse output and the new, alternative 
'text mode' menu).

I simply cloned the main repository again, and synchronized the files 
with my local repository (DL4YHF branch) with the 'fresh' main 
repository. This also reduced the size of the zipped repository from 
almost 80 MByte to about 54 MByte. The revision history of my own 
changes got lost this way (but of course not the revision history of 
other contributors). So far, no more merge conflicts, and even the 
'Travis CI' build processed finished flawlessly with both build 
environments. Sigh..

Anyway, I deleted the old PR (#734 with many dozens of small 
modifications) and replaced it by PR #741 which should be easier to 
merge. There's a minor thing left to do (related with the codeplug 
structure used inside the SPI flash, which I cannot validate for GPS 
devices / S13.020), but that's another topic.

All the best,
   Wolf .

Am 08.05.2017 um 02:10 schrieb Schuyler St. Leger:

**Pull request closed without merging**
