### PR TITLE
adding netmon5 and latest changes including #652, #663, #674

### PR DESCRIPTION
**Pull request by DL2MF**
I have merged my PR with already Clay's latest PR included due to extended testing with MD390/G.

Now, due to the delay of several PR's and my continously development on some of the latest PR's I have included my keyb.c into this fork.

Please take a second and let's have a look at my suggest of a new keyboard & functions layout:
============================================================================

```
+-----+-----+-----+-----+
!  1  !  2  !  3  !  *  " 
+-----+-----+-----+-----+
!  4  !  5  !  6  !  0  " 
+-----+-----+-----+-----+
!  7  !  8  !  9  !  #  " 
+-----+-----+-----+-----+ 
```

Current official keyboard assignment:
=============================
1 - SMS-Test
2 - Netmon5 (new 01/2017)
3 - Copy dst to contact (new 11/2016)

4 - Netmon4 (new 11/2016)

5 - clear syslog (new 10/2016)
6 - syslog dump

7 - Netmon off

8 - Netmon1
9 - Netmon2
'# - Netmon3

My suggest for a clean UI and (fmpov) better handling (for right-handed users):
===============================================================
1 - SMS-Test
2 - spare 
3 - Copy dst to contact (this is nice assigned with the arrow down key above as a hint symbol!)

4 - Netmon4 (lastheard calls)
5 - Netmon5 *  (lastheard call&channel)
6 - Netmon6 *  (lastheard channel)

7 - Netmon1 *
8 - Netmon2 *
9 - Netmon3 *

'* - syslog dump *
0 - clear syslog *
'# - Netmon off *

'* - reordered keys (7,8,9,# will only wrap around 1 position)

Only two keys, "syslog dump" (old:6 new:*) and "clear syslog" (old:5 new:0) move positions, Netmon5&6 are new, the bottom line only wraps around its order.

The Zero-key "Null" will null/clear the syslog, other keys swapped remain in the same function blocks without unintentional causing a function or deleting something.

The right column will be used to clear or exit from a function (like the red special key above it), the left 3 columns activate or display something.

### CODE REVIEW

**Comment by DL2MF** [comment]
Hi Travis,

how about a merge of my PR now, my development branch still hangs on this?

Regards,
Mike

**Comment by travisgoodspeed** [comment]
Howdy @DL2MF,

I'm not quite sure from the description what this patch is supposed to do.  Is it to reorder to the buttons, or to add logging, or what?  What are slog.c and clog.c?  What features are added?

73 from Philly,
--Travis

**Comment by DL2MF** [comment]
Hi Travis,

there are two new LH screens (netmon5&6) that extend the functionallity of my former netmon4/LH-list.

Due to the fact, that I currently have no scrolling implemented, netmon5 gives you at the end of the LH log in line 9 the latest channel name additionally to logged call, on which the latest activity has been monitored and a page counter.

Netmon6 logs no callsigns but channel names on which activity has been monitored.

Both functions have been realized with slog (station log) & clog (=channel log) to be able to clear the logscreens independently (may be integrated in one multifunctional log in future revisions).

The features have been tested for a few weeks, on channels or during times like the weekly WW net on TG91 and in scanning mode these new features are very helpful, because netmon4 is currently limited to only 10 entries of last heard stations.

73 from Hannover/Celle region,
Mike

**Comment by travisgoodspeed** [comment]
To prepare for a merge, could you please update this branch with the following:
- [ ] An accurate and complete description in the title and body of the pull request.  (Not just comments.)
- [ ] Resolve the merge conflicts in `keyb.c`, `menu.c`, and `fixed.csv`.
- [ ] Add comments to `slog.c`, `clog.c`, and any other new functions or files.

Keyboard layout changes should probably be in separate pull requests from features, but we'll see what can be done.

73 from Philly,
KK4VCZ

**Comment by DL2MF** [comment]
Due to the huge number of changes in the meantime I'm now still working on the current official build and I think it's a better idea when I will make a new pull request with my latest netmon changes.

73 Mike, DL2MF

**Pull request closed without merging**
