### PR TITLE
backlight control modified, suspected CPU reset when turned on too early

### PR DESCRIPTION
**Pull request by Wolf-DL4YHF**
SysTick_Handler now "waits" until the original firmware turns backlight on, then takes over control, and starts dimming.

Old backlight control may have turned BL on too early, when power supply had not ramped up completely (drawing too much current, depending on BL configuration). 

No need to initialize from splash_hook() anymore (which may have been "too early"..)

Details in irq_handlers.c .

### CODE REVIEW

**Comment by Wolf-DL4YHF** [comment]
Aaargghhh .... so many differences now ... there must have been tab characters in a file before 
- my excuses. I personally hate tabs in source files, and never insert tabs anywhere (I kill them where I see them, an old habit..) .

**Comment by Wolf-DL4YHF** [comment]
Can anyone explain why "all checks have failed" ? The mumbo-jumbo at the above 'Details' link doesn't indicate if this a problem with the modified C sources, or whatever. Too many warnings (about non-declared functions being called), etc etc etc, but those warnings must have been there before.

**Comment by travisgoodspeed** [comment]
Looks like checks were failing a few revisions back, but the current version of this branch is passing.  Sometimes it takes a while to update.

**Comment by travisgoodspeed** [comment]
Self assigned for testing.  I hope to merge this tonight.

**Comment by travisgoodspeed** [comment]
Testing on D13 and S13, the only problem I can find with this was actually introduced by me in f299c1d9e7100f3a01941c1b1086562750ca4d28.  I'm going to merge this first, then patch that, and we'll be good to go.

**Pull request merged**
