### PR TITLE
Fixed missing gfx_info on D02 version for new bootscreen.

### PR DESCRIPTION
**Pull request by xSmurf**
Fix for the previous PR.

### CODE REVIEW

**Comment by xSmurf** [comment]
Shoot yeah conflicts, if you prefer I'll close it and fix it by deleting my branch, and started from scratch.

**Comment by sijskes** [comment]
better not delete your branch. thats where all the work is. let me do this one time.

**Comment by xSmurf** [comment]
Well I can just copy it to the side for a bit and do a manual merge in fresh branch I really don't mind if it makes your life easier.

Sorry about the rough merge, I promise I'll do better next time :)

**Comment by sijskes** [comment]
merged 2 commits. can you verify?

**Comment by xSmurf** [comment]
Sorry took me a while to verify due to the ongoing global DNS/DDoS issues today... everything seems AOK!

Thanks for helping out on my first PR to the project :)

**Pull request closed without merging**
