### PR TITLE
auto line wrapping on console output

### PR DESCRIPTION
**Pull request by iddq**

### CODE REVIEW

**Comment by iddq** [comment]
sorry, what is wrong?

**Comment by sijskes** [comment]
there are 2 ways of printing foreseen, methods with wrap, methods without.

**Comment by sijskes** [comment]
@iddq thanks for the effort. i'm splitting the 2 interfaces now.

**Comment by sijskes** [comment]
@iddq not wrong perse, but i didn't fix any bug, and it removed  foreseen but not implemented functionality.

**Comment by iddq** [comment]
the reason of the modification is I would like to send longer messages by LOGR

**Comment by sijskes** [comment]
@iddq there is not much visual space to show long lines. can't you insert a \n somewhere in your LOGR printf? the line counting algo will be off as well if you implement wrapping in the console code.

**Comment by iddq** [comment]
which line counting algo? con_nl() increases the con_ypos

**Comment by sijskes** [comment]
the syslog interface is not the same as the console interface.
the syslog interface will allow for display on the console.
line counting and preparation for scrolling is done code around the lines[] array in syslog.c
please leave unfinished scrolling logic intact unless you intent to implement it.

**Comment by iddq** [comment]
yes, I'm also trying to fix the scrolling issues.

**Comment by sijskes** [comment]
@iddq ah, you mean scrolling back and forth with the arrow keys?

**Comment by sijskes** [comment]
I've opened an issue on it: #465

**Pull request closed without merging**
