### PR TITLE
The Russian language is added

### PR DESCRIPTION
**Pull request by s-s-s**
The Russian language is added

### CODE REVIEW

**Comment by dragstor** [comment]
@s-s-s, there will be issues with displaying Cyrillic letters in menus. Tried it myself for the Serbian translation. You'll get something like this. "??? ????? ??? ??".

Also, keep in mind that no string should be longer than mentioned in the comment line, just before the English example :)

**Comment by s-s-s** [comment]
> there will be issues with displaying Cyrillic letters in menus. Tried it myself for the Serbian translation. You'll get something like this. "??? ????? ??? ??".

It is a great pity if this is so.
I thought the UTF-8 encoding would help us.

**Comment by travisgoodspeed** [comment]
The MD380 uses UTF16 internally, but it only has Chinese characters and the ASCII subset of the Latin alphabet.  Sorry about that.

**Comment by s-s-s** [comment]
Waiting for utf8

**Pull request closed without merging**
