### PR TITLE
Md380 fully semi automatic upgrade

### PR DESCRIPTION
**Pull request by mach327**
This required the name change for the stm32-dfu file so it could be used as a module.
`stm32-dfu` becomes `stm32_dfu.py` and a wrapper `stm32-dfu` is added for compatibility.

This allows for unattended upgrades (if you have a battery eliminator, anyway).
Firmware upgrades, once you have flashed a md380tools radio firmware compiled since yesterday, can be completely unattended, with no manual intervention required.
Take note - using the reboot_to_bootloader feature _erases a sector of flash_, so there's no undo and a firmware upgrade is *required* once reboot_to_bootloader is used.

I'd like some help testing this, since I currently only have an MD380G in VHF to test with. (I'll have a few more radios back in a week or so.)

For googlers and users:
This new ability will _not_ work unless you have installed the master branch md380tools firmware on the radio since yesterday. If a firmware upgrade appears to have no effect, use the usual method of entering the bootloader by holding PTT and the orange button above PTT while turning on the radio, and try flashing again. You are only in the bootloader if you see a red/green alternating status LED. The radio must have this red/green LED flashing before the new firmware is actually sent to the radio, or it will fail.

### CODE REVIEW

**Comment by KD4Z** [comment]
I'm game for testing this on the UHF 380 @mach327    It will have to wait until we get past this weekend..it's Field Day here in the states :)

**Comment by mach327** [comment]
@KD4Z I'm participating too! I'm in the FN41, FN42 area, I'll keep an ear out for your call.

**Comment by stefansaraev** [comment]
you forgot to ```git add stm32_dfu.py```

other than that it works for me, MD380 without GPS. copied old stm32-dfu as stm32_dfu.py and imported usb.core on top. I'll re-test when you push the file (in case you have other stuff changed..)

**Comment by mach327** [comment]
Oh man, I did! Thanks for catching that.

**Comment by stefansaraev** [comment]
thanks. wfm.

unrelated to this particular feature, but it would be nice if you guys change your git workflow a bit, use ```git rebase -i origin/master``` instead of git merge, that would result in much cleaner PRs and easier testing ;)

**Comment by mach327** [comment]
Thanks for the testing.
Yeah, I saw that history didn't look super pretty. I'll read up and try it!

**Comment by KD4Z** [comment]
@mach327   Kewl   We are K4JJ 3A,  Georgia, plus 6m, GOTA and full azel Sat station.  My coffee table looks like a mushroom farm here growing laptops getting N1MM+ configured for the FD effort.  In the last 3 yrs, we were #1, #1, #3 in 3A.   Last year we ate too much BBQ.  Anyway, I digress..Sorry for the noise.

**Comment by mach327** [comment]
That's impressive! This'll be my first real field day, I'll see if I can snag your group. Listen for the weakest signals, I'll be QRP. :smile:

**Pull request merged**
