### PR TITLE
full screen RX popup

### PR DESCRIPTION
**Pull request by hsmade**
I think this integrates a bit nicer with the original OS UX design.
The RX popup is now full screen and blue. It has the call sign in the big font.

### CODE REVIEW

**Comment by m1eqb** [comment]
The RX popup is now full screen and blue. It has the call sign in the big font.i to would like to have the screen in full and the bigger text  blue or green set by user

**Comment by aeickho** [comment]
there locks nice, but the name is not shown .. see picture

**Comment by hsmade** [comment]
I don't see a picture?

**Comment by aeickho** [comment]
it is on the line .... my internet access is extreme limited ...  German Mobile Internet ;)

**Comment by aeickho** [comment]
x1

**Comment by hsmade** [comment]
I will rebase and check it in a few hours (meetings, meetings...) 
I actually had all info on mine, so it must be something simple.

**Comment by aeickho** [comment]
I confuse ...
    my name is still overwritten...  

line 1 src
line 2 _big_ call
**line 3 name overwritten by from->to** 
line 4 village 
line 5 Country

**Comment by hsmade** [comment]
Hmm, not with my md380. I moved the from->to to Y_START, which is src. I just asked for simon/roeland to test it locally to check. We're on a telegram chat and local channel which is a bit easier to debug :)

**Comment by hsmade** [comment]
@sijskes checked my branch, works for him as well. Can you please flash and check again?

**Comment by aeickho** [comment]
@hsmade I'm not very happy with this patch 

the big call is nice

but that the info is displayed only if rx: is not so good... my gray screen was nice

**Comment by hsmade** [comment]
Could you elaborate on that? The green screen was also only displaying on RX, or? And they gray screen is still there at the end of RX? Or do you see something else?

**Comment by aeickho** [comment]
OK ... 
  It's works there is no gray screen on simplex channel
 
Sorry

**Comment by hsmade** [comment]
That's weird. I didn't change that code. I only changed the inner of print_rx_screen and the color + name of rx_screen_green_hook. So the gray screen should appear as before. Could you verify that it did before my changes?

**Pull request merged**
