### PR TITLE
Advanced statusline, sidebutton extension, display RX/TX freq from CP 

### PR DESCRIPTION
**Pull request by DL2MF**
This PR is providing all latest changes:
- advanced status display (CC/TS/TG in a new compact statusline above channel name)
- DCS, CTS and TS/TG info for each channel
- show RX/TX of selected channel below channel name
- enable promicuous mode or mic gain via sidebutton
- enhanced sidebutton options for new features

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
Looks like a few warnings need to be cleaned up before merging.

```
arm-none-eabi-gcc -std=gnu99 -g -O2 -Wall -Tapplet_d02.032.ld -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar -Wa,-a=amenu_channels.lst -DFW_D02_032	 -Werror -Wno-cpp -Iinc -Ilib -Ilib/inc -I. -Ilib/inc/core -Ilib/inc/peripherals -D "MD380_d02_032"     -c -o amenu_channels.o src/amenu_channels.c
src/amenu_channels.c: In function 'readTone':
src/amenu_channels.c:148:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  if (*(uint16_t*)&chan->settings[(fEnc ? 26 : 24)] == 0xFFFF) {
  ^
src/amenu_channels.c: In function 'ParseChannel':
src/amenu_channels.c:228:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[3]: *** [amenu_channels.o] Error 1
make[3]: Leaving directory `/home/travis/build/travisgoodspeed/md380tools/applet'
make[2]: *** [image_D02] Error 2
make[2]: Leaving directory `/home/travis/build/travisgoodspeed/md380tools/applet'
make[1]: *** [ci] Error 2
make[1]: Leaving directory `/home/travis/build/travisgoodspeed/md380tools/applet'
make: *** [ci] Error 2
The command "bash -x ci-script.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by DL2MF** [comment]
Worked today on compatibility to D02 firmware, will check the differences of warnings to my local compiler results.

**Comment by travisgoodspeed** [comment]
Run `make ci` to do the same sort of build that the CI server does.  I think it's stricter about warnings, treating some of them as errors.

**Comment by DL2MF** [comment]
Still working on this, fixed some warnings but a few still remaining. Todo for this weekend.

**Comment by stefansaraev** [comment]
fyi I have rebased this PR on top of master and made "make ci" happy (I dont pretend I've dont it right) at https://github.com/stefansaraev/md380tools/tree/pr821-rebase

the whole thing needs a bit of cleanup, and I've noticed some annoyances but IMO this feature is good enough to go into master (tbh, I can test the sms thing, but extended display and sidebutton functions are nice!) 

feel free to continue from here if it helps

**Comment by DL2MF** [comment]
Tnx @stefansaraev  for working on the cleanup. Finally found some time during the last week to fix the latest compiler warnings and test this build. @travisgoodspeed should be fine now to me merged.

**Comment by travisgoodspeed** [comment]
Thanks, @stefansaraev and @DL2MF!  Merging this now.

73 from Reno,
--Travis KK4VCZ

**Pull request merged**
