### PR TITLE
db: switch to ham-digital and minor cleanups

### PR DESCRIPTION
**Pull request by stefansaraev**
radioid.net people are scared of GDPR and removed all 2xx IDs. let's use ham-digital db.

### CODE REVIEW

**Comment by mach327** [comment]
Looks good to me, but I won't claim I understand why radioid.net is scared of the new laws but ham-digital.net isn't.

**Comment by mach327** [comment]
Thanks!

**Comment by KD4Z** [comment]
I've wondered that too.  Radioid has full data but is missing 2nnnnn ids.  ham-digital has all ids, but has redacted most of the good stuff.  I resorted to pulling down both and merging them with field level priority in my Toolkit.   Radioid isn't stable either.  A few days back, they had a blank file posted for days.

**Comment by travisgoodspeed** [comment]
*Error 451: This comment is not available in your region due to Privacy and Electronic Communications Directive 2002/58/EC.*

**Pull request merged**
