### PR TITLE
fix compile warnings

### PR DESCRIPTION
**Pull request by iddq**

### CODE REVIEW

**Comment by Wolf-DL4YHF** [comment]
Don't merge this !!
It will remove warnings, maybe, but the intention of "log" isn't as you guessed it was !
Mike, DL2MF, please comment. 
My guess: "log" was intented to be a char, NOT a "char pointer".

**Comment by DL2MF** [comment]
Yes, this PR should not be merged, my current branch or Wolf-DL4YHF's PR will fix this soon.

**Comment by DL2MF** [comment]
@travisgoodspeed The changes have been merged with current builds by Wolf and me, this pr may be closed.

**Comment by travisgoodspeed** [comment]
Cool.

**Pull request closed without merging**
