### PR TITLE
get_dmrmarc_json.py: clarify python-request requirment

### LINKED ISSUE #859: get_dmrmarc_json.py causes updatedb failure
The creation/addition of the new python script, get_dmrmarc_json.py, caused my updatedb process to stop working.

Digging through the file/makefile for db revealed the get_dmrmarc.errors file, which showed I was missing the requests python module.

Suggest adding better error message/handling around this, to inform user of the new required 'requests' module they may have to install to bring updatedb back to a working state.

### PR DESCRIPTION
**Pull request by stefansaraev**
closes #859

@KD4Z are you ok with this ?

### CODE REVIEW

**Comment by KD4Z** [comment]
I'm still in the camp that likes to see errors separated from the data as an exception report.   I believe it might be hazardous to have errors tossed into the standard output file.   Certainly would confuse the radio if it gets written into the radio that way.   

Good show on the move for request inside the Try.   I have run into two instances this week, of users having issue with the script failing without request being installed.  It seems that Linux Mint comes out of the box without it.    We need an addition to either the debian.md or add one for Mint, that adds a prerequisites for python-pip and request.  Can you add that as part of your PR?

**Comment by stefansaraev** [comment]
any python errors (the traceback that comes aout of it) always go into stderr, nothing bad will happen. and for this very special where I catch the error and print something, I make sure to also print it on stderr.

I could as well not try-catch at all, and it would still be fine. but I decided to print a bit more informative message instead.

I'll add python-requests to readme.md files

**Comment by KD4Z** [comment]
Ok, I could a swear you had stderr redirected to  $@   That will teach me to look at this stuff on a cell phone display :)   Looks good now.

**Comment by stefansaraev** [comment]
another alternative: https://github.com/stefansaraev/md380tools/commit/7f11387ba4c562f38f51b47c956737a6fcb3b63b

**Comment by travisgoodspeed** [comment]
Merging from @KD4Z's review.  Thanks for the PR, @stefansaraev!

**Pull request merged**
