### PR TITLE
screenshot via USB with output as bitmap file

### PR DESCRIPTION
**Pull request by Wolf-DL4YHF**
Usage:
python md380_tool.py screenshot

Requires experimental firmware with new lcd_driver.c and usb.c

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
@Wolf-DL4YHF Is this ready to merge?

**Comment by Wolf-DL4YHF** [comment]
It was, but not sure about compatibility with the recent additions to 
the main branch.
Let me check myself in a couple of days, maybe I will also add the 
'doubleclick feature' to invoke the talkgroup entry in the new menu.
At the present time, busy from other interests / duties...

Am 31.08.2017 um 17:25 schrieb Travis Goodspeed:

**Comment by KD4Z** [comment]
@Wolf-DL4YHF   Working well Wolf.   Occasional frame glitch, a lot like it was doing a refresh when the capture buffer was grabbed, but no biggie..   I've added a special command in my VM Toolkit so others can easily build and test from your master branch.  ( "glvwolf"   instead of "glv")   @DL2MF has one too ("glvmike")     Otherwise, it builds correctly now and seems good to go.

**Comment by Wolf-DL4YHF** [comment]
Thanks - and indeed my RT-3 also occasionally delivers a single 'black 
line' in the live display, when periodically read out via USB from
'md380remote.pyw'. Guess the problem is the delicate timing of the LCD 
controller (for which we don't have a 100%-matching datasheet), or a 
simultaneous access to the display from the USB handler and some other 
task that accesses the LCD.

Cheers,
  Wolf.

Am 22.09.2017 um 16:02 schrieb KD4Z:

**Pull request merged**
