### PR TITLE
Polish regional talkgroups and services

### PR DESCRIPTION
**Pull request by bilbolodz**
Added Polish talkgroups and services from https://bm.pd0zry.nl/index.php/Poland

### CODE REVIEW

**Comment by phl0** [comment]
This would break up the sorted structure of users.csv. The pull from BM inserts IDs in the range of 4000 to 4999. Your PR would insert the Polish IDs with values of 260, etc. after this.

**Comment by bilbolodz** [comment]
So maybe it could be a good idea to merge all files (I suggested to add also "local_user_special.csv" file), sort it out and the put it into radio.

**Comment by phl0** [comment]
Jupp I am currently looking for a portable solution to sort the users.csv after all data is pulled.

**Comment by travisgoodspeed** [comment]
We really need a proper tool to manage all of these different User and TalkGroup databases.  Any volunteers?

**Comment by phl0** [comment]
I am working on this in #136. I have some support from the BrandMeister developers to pull the data direclty of the BM master servers. So suggest we leave it for now (as it would break the sorting).

**Comment by phl0** [comment]
Python script added to fetch these IDs automatically - though that is not yet available from the Polish master.

**Comment by aeickho** [comment]
hy @bilbolodz  @phl0 
  can we close this pull request now, is this completely handled by #211?

-alex

**Comment by phl0** [comment]
It is handled by @211 as soon as the Polish master server serves its list with the special IDs. Currently it is only the Russian master that provide the info. But all masters will soon get an update that enables the function that provides the IDs for my python script.

**Pull request closed without merging**
