### PR TITLE
Update DMR IDs

### PR DESCRIPTION
**Pull request by phl0**
Just an update of User IDs as I just did it anyway on my radio =)

### CODE REVIEW

**Comment by dl8bb** [comment]
It makes no sense to edit these files because they are automatically generated during the make process.

**Comment by der-stefan** [comment]
According to #95 the list should be removed anyway from the repository. Let's add it in the .gitignore list.

**Comment by phl0** [comment]
Good idea.

**Comment by phl0** [comment]
Better have it like this: https://github.com/travisgoodspeed/md380tools/compare/master...phl0:ignorelists ?

**Comment by aeickho** [comment]
@travisgoodspeed what is your opinion on this item?

**Comment by travisgoodspeed** [comment]
I don't mind removing it from the repo, but at the very least, it ought to be ignored by Git.

**Comment by phl0** [comment]
So shall I make a pull request from my branch mentioned above?

**Comment by dg9vh** [comment]
@phl0 I think a pull request would be the best :smile:

**Comment by phl0** [comment]
[x] done. Let's see what @travisgoodspeed has to say to #111 :-)

**Pull request closed without merging**
