### PR TITLE
Rename files to allow importation as a module

### PR DESCRIPTION
**Pull request by mach327**
The md380-* file naming scheme breaks Python module import.
Fixing this would be helpful for the Chirp driver to allow upload and download.

This commit renames them to a `md380_*.py` scheme, allowing import like `md380tools.md380_dfu`
It also fixes all references I could find to the affected files.

### CODE REVIEW

**Comment by aeickho** [comment]
I don't know the answer to that. Python is an big mystery for me. I'm not extreme happy with this change. But I can live  with her.

**Comment by travisgoodspeed** [comment]
No objection to changing the filenames, but it'll be a hassle for everyone involved, so let's be careful to do the renaming exactly right on the first try. 

We should avoid underscores in executable names, even just for scripts. This might also be a good time to switch to varargs for interpreting the command line arguments.

**Comment by mach327** [comment]
Agree on hassle and getting it right the first time.
Only reason I went with underscores is because it was closest to the current system that was compatible with importing, I'm not attached to the scheme at all.

If not underscores, not symlinks, and not dashes:

* md380tools.py, md380dfu.py, md380gfx.py, md380fw.py
* mdtools.py, mddfu.py, mdgfx.py, mdfw.py
* 380tools.py, 380dfu.py, 380gfx.py, 380fw.py
* tools.py, dfu.py, gfx.py, fw.py
* something else?

I can't say I'm convinced of any of the above. The first set and last set seem least offensive.

I'd love to just symlink a nice name to the python files and commit those, except that doesn't seem to be well supported on Git for Windows platforms. I tried to just symlink a python-import friendly name pointed at the current names, except I ran into "Too many levels of symlinks" issues.

**Comment by ajorg** [comment]
What I've done in my own Python projects is to move all logic (usually including main()) out of the script and into a module, leaving only the argument parsing and a call to main in the non-.py script.

**Comment by travisgoodspeed** [comment]
I like @ajorg's solution best.  Any volunteers to do that refactoring?

73 from Philly,
--Travis

**Comment by mach327** [comment]
I'll grab it. Will make reference to and close this PR when I have something. (Might take a day or two to find the time.)

**Comment by aeickho** [comment]
f2

**Pull request closed without merging**
