### PR TITLE
fw encryption key for md9600

### PR DESCRIPTION
**Pull request by KG5RKI**
Figured out encryption key for md9600 fw.  Use it like you do for md2017.

EDIT: Also works on RT90 fw, if you hadn't guessed..

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Very interesting.

**Comment by KG5RKI** [comment]
> Very interesting.

hey @rogerclarkmelbourne can you hit me up at tydweaver@gmail.com? I wanna share something with you privately, in case it is helpful to you.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I sent you an email

FYI. There are a couple of guys in Italy porting the OpenGD77 to the MD-380, but the radios which uses the AT1846S RF chip (and the C6000) are an easier target, and I suspect the MD-9600 is one of these, because TYT seem to use the AT1846S their dual band radios.

The MD UV-380 definitely uses the AT1846S, but I don't know if the bootloader is the same on this radio, which would allow the encryption to be broken.

**Comment by KG5RKI** [comment]
mduv380 uses a bootloader that is the same or more similar to the md2017.  Unfortunately, Travis' trick to dump the bootloader does not work on anything I have tried except md380, so I had to find a new way to get the encryption keys. The mduv380/390/rt3s use the same encryption key as md2017. Interesting enough, if you change the radio identifier using the factory util to make it match a 2017 for example, it will run fw meant for a 2017 (with bugs ofc, but still interesting).

**Comment by rogerclarkmelbourne** [comment]
@KG5RKI 

Thanks.

If the encryption key / hash table is known, then I presume you can encode your own application code and get the bootloader to accept.

So to dump the bootloader just requires an application to be written which enumerates on USB as a COM port, and it could then just dump the bootloader as hex bytes into a terminal program.

This would not be super efficient, but would probably be the easiest way to get the bootloader binary

Once the binary has been downloaded, it can be patched using Ghidra to remove any nasty code that disables the SWD and read protects the MCU, and then the new booloader can be flashed on via SWD.

I'm not sure how advanced they are with their code, but the Italian guys porting the OpenGD77 to the MD-380 may have a version which has functional USB COM (CDCACM)

**Comment by rogerclarkmelbourne** [comment]
BTW. Please feel free to email me roger at rogerclark.net

**Comment by n1zzo** [comment]
Indeed we have a working USB COM, we have also support for:
- GPIO
- encoders
- ADC (sensors)
- display
- DMA (on sensors and display)
- timers
We are slowly working out the RF part now.

**Comment by KG5RKI** [comment]
you can dump the bldr if you want, I did it by just modifying the firmware to write it to the external spi which I then dumped with hardware cause I was too lazy to hook up uart to it lol.  Anyway, if you just setup some fw with the same base address and wrap it using the keys I've provided it will flash without any issues.  Don't forget to fix up the header and include the resource binary at the front.  Like I said, same process as md2017.

**Pull request merged**
