### PR TITLE
fix issue #2

### PR DESCRIPTION
**Pull request by der-stefan**
This workaround only checks for the file ending. This is not secure and should be improved!

### CODE REVIEW

**Comment by aeickho** [comment]
@der-stefan please added some note about the usage in the md380-dfu usage section

**Comment by aeickho** [comment]
@mach327 @travisgoodspeed what do you all mean? about  the md380-dfu addition

**Comment by dg9vh** [comment]
@aeickho I think if the filesize of the rdt-file is checked also problems would be minimized because all codeplugs has the size of 262709 Byte. If some header-checkings are also done, this way would be safe enough in my eyes... but this are only my 2 cent.

**Comment by der-stefan** [comment]
Now the check should be bullet-proof: File ending, size and first five Byte.

**Comment by der-stefan** [comment]
Anything missing or should be improved?

**Comment by dg9vh** [comment]
@der-stefan  From my point of view after serveral times of testing it with my codeplugs and RT-3/MD-380 HTs I would say it would be ok.

So now it's @aeickho 's or @travisgoodspeed 's part to merge it into the master.

**Comment by travisgoodspeed** [comment]
Merging, but we should have a separate patch to read an RDT properly, with the right header and footer.

**Pull request merged**
