### PR TITLE
Fix Backlight menu

### PR DESCRIPTION
**Pull request by stargo**
Add ability to store changes on S13.020 and display the currently selected backlight timeout.

### CODE REVIEW

**Comment by PD1WP** [comment]
Iis this feature only available for the GPS version or also for the TYT md-390 without GPS

**Comment by Wolf-DL4YHF** [comment]
Umm.. MD-390 without GPS ?
For the MD-380 and RT3 (always without GPS), the modification works (I 
merged and tested it into my temporary branch with the *dimmed* 
backlight now).

What the mod does not fix (at least not here) is the "blue disc" marker. 
I still don't understand what controls it (blue disc in the circle... 
doesn't scroll properly).

Cheers,
   Wolf DL4YHF .

Am 29.01.2017 um 09:54 schrieb PD1WP:

**Comment by stargo** [comment]
I've tested it on a MD-380G (with GPS) and a MD-380 without GPS, so it should work on a MD-390 without GPS (if there is such a thing) witjh the D13.020 firmware.

On the non-GPS units, the selection was already saved in flash, this was only missing for the GPS-models (which is added by the first patch in this PR).

I also don't know what exactly triggers the blue discs to work

**Comment by DL2MF** [comment]
The "blue disc" usually called "radio button" in programming IDE's is only a visual marker for the selected entry. But you can prove very simply that storing the selected setup works fine, when using the sidebutton modification with it's long selection list. 

When you recall a setting, the correct menu entry is listed active, but missing the radiobutton marker. I've also had a brief look on this a few weeks ago but working on some netmon enhancements since that time. As far as I noticed, it works fine for the first 4 entries of a list (like most factory settings) but is corrupt for md380tools setup options with more. May be a corrupt index or value overflow.

I've included this patch by stargo also into my fork with Clays sidebutton menu, an additional improvement to that giving detailed feedback info when saving selection and the latest netmon6 channel list in my latest fork (but be aware, my keyb layout is slightly different (see PR #663).

**Pull request merged**
