### PR TITLE
HRC5000 new FM features

### PR DESCRIPTION
**Pull request by DL2MF**
The new module system_hrc5000.c gives access to several analog FM features of the radio chipset. The user can set FM bandpass filter, compressor, preemphasis, bandwidth 12.5/25.0 kHz and deviation. Due to these experimental features, they must be enabled in the new submenu [5] DevMode Level of the developer menu. 
Another addition is concerning the keyb scroll feature, this now can be selected disabled/fast/slow in Keyb setup.
All modifications and new features have been tested on different radios from Tytera and Retevis, the feedback of all beta tester was 100% issue free.

### CODE REVIEW

**Comment by DL2MF** [comment]
Seems not to be my issue, gcc completed successfully, clang for Mac OS X failed with missing ressources:

`Error: Failed to download resource "gcc-arm-none-eabi"

Download failed: http://px4-travis.s3.amazonaws.com/toolchain/gcc-arm-none-eabi-5_4-2016q3-20160926-mac-d.tar.bz2

The command "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew install gcc-arm-none-eabi; fi" failed and exited with 1 during .

Your build has been stopped.`

**Comment by travisgoodspeed** [comment]
We really ought to cut OSX out of the CI pipeline.  You're right that it's a random failure and that the code builds properly on Linux.

**Comment by roelandjansen** [comment]
I am all in for that. Only target to CI/CD is linux. Makes support/bughunting easier as well.

**Comment by travisgoodspeed** [comment]
I've disabled OS X builds from the master branch.  Current pull requests aren't affected yet, of course, but future ones will avoid these false failures.

**Comment by DL2MF** [comment]
OK, should I retrigger my open PR's again?

**Comment by mach327** [comment]
err, did not mean to request a review, sorry!

**Pull request closed without merging**
