### PR TITLE
Adding netmon5 / additional lastheard with channel info

### PR DESCRIPTION
**Pull request by DL2MF**
fix background lastheard Netmon4 (Key 4) and new Netmon5 (Key 2) with channel info. This may be helpful during scan - Please note: in promiscious mode your radio may stop on many channels!

Suggesting reordering of keyb to keep Netmon functions together:
Netmon4 - key 4
Netmon5 - key 5 (swap with #2?)

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
Just checking: Does anyone with commit rights object to the proposed keypad reordering?

**Comment by sijskes** [comment]
re: keyordering. i see no real use for re-ordering, i find it confusing to users to re-order keys that have been there for about a year now.

**Comment by DL2MF** [comment]
As far as I can see, key "5", that is in discussion to be swapped with currently unused/new assigned key "2" has been introduced on Oct, 7th with PR "syslog tail scrolling" #0277044.

The layout makes no difference to me, cause in my own fork I'm using another key layout since introducing netmon4, when we had this discussion first time.

But take a few minutes and let's have a look at the current keyboard & functions:

```
+-----+-----+-----+-----+
!  1  !  2  !  3  !  *  " 
+-----+-----+-----+-----+
!  4  !  5  !  6  !  0  " 
+-----+-----+-----+-----+
!  7  !  8  !  9  !  #  " 
+-----+-----+-----+-----+ 
```
1 - SMS-Test
2 - Netmon5  (new 01/2017)
3 - Copy dst to contact (new 11/2016)
4 - Netmon4 (new 11/2016)
5 - clear syslog (new 10/2016)
6 - syslog dump
7 - Netmon off
8 - Netmon1
9 - Netmon2
# - Netmon3

To be honest, my suggest for a clean UI and (fmpov) better handling (for right-handed users):

1 - SMS-Test
2 - remain spare
3 - Copy dst to contact (this is nice assigned with the arrow down key above as a hint symbol!)

4 - Netmon4
5 - Netmon5  (*)
6 - syslog dump
0 - clear syslog (*) 
7 - Netmon1 (*)
8 - Netmon2 (*)
9 - Netmon3 (*)
# - Netmon off (*)

(*) - reordered keys

The Zero-key "Null" will null/clear the syslog, other keys swapped remain in the same function blocks without unintentional causing a function or deleting something.

**Comment by DL2MF** [comment]
I'll start a new PR with some additional minor changes.

**Pull request closed without merging**
