### PR TITLE
Hooks µcos functions

### PR DESCRIPTION
**Pull request by aeickho**
Travis,
  is this patch of interest?

experiment with hooks and the µcos 

alex

### CODE REVIEW

**Comment by travisgoodspeed** [comment]
I'm very interested in accessing µC/OS-II functions, but I can't quite merge this pull request as it stands.

The function that you call `OSTaskCreate()` at 0x804bbf4 is actually `OSTaskCreateExt()`, which takes no fewer than nine parameters.  I think your patch works because those extra parameters happen not to be clobbered, but I'd like to know that they are all properly passed before merging.  http://sigpromu.org/brett/elec3730/quickref.html#OSTaskCreateEx

Two useful functions for `os.c`:
1) `OS_ENTER_CRITICAL()` is at 0x08041df8
2) `OS_EXIT_CRITICAL()` is at 0x08041e00

Please correct the calling convention and re-assign to me for merging.

**Comment by aeickho** [comment]
ok..  i'll correct the calling convention tomorrow ... tnx for our report

**Comment by aeickho** [comment]
@travisgoodspeed 
- [x] OSTaskCreateExt()  correct the calling convention

**Comment by aeickho** [comment]
now i work on the hooks for:
1) OS_ENTER_CRITICAL() is at 0x08041df8
2) OS_EXIT_CRITICAL() is at 0x08041e00

with output calling function address.

**Comment by travisgoodspeed** [comment]
OS_ENTER_CRITICAL() and OS_EXIT_CRITICAL() are very useful to call, but we probably don't want to hook them, as they are called in many portions of the code for wildly different reasons.

Merging.

**Pull request merged**
