### PR TITLE
Modified error-handling on non-responding servers

### PR DESCRIPTION
**Pull request by dg9vh**

### CODE REVIEW

**Comment by aeickho** [comment]
hi @dg9vh,
  You have an idea why the tests fail?

-alex

**Comment by dg9vh** [comment]
Not real. On my local Debian 8 64bit machine it works...Maybe one could test it on other systems to cfm?KimAm 09.12.2016 19:14 schrieb "alex, df8av" <notifications@github.com>:hi @dg9vh,
You have an idea why the tests fail?
-alex

**Comment by sijskes** [comment]
it used to be a soft-fail, not? what problem does it fix?

**Comment by dg9vh** [comment]
It fixes the error, if a server is not responding and a socket timeout occurs.Actually, the script crashes down with stack trace.KimAm 10.12.2016 00:03 schrieb Simon IJskes <notifications@github.com>:it used to be a soft-fail, not? what problem does it fix?

**Comment by sijskes** [comment]
superseded by #639

**Pull request closed without merging**
